package ticket_reservation_system;

public class Main {

	public static void main(String[] args) {

		Flight flight = new Flight();
		
		System.out.println("Flight 562 - Frankfurt to Yerevan".toUpperCase());
		System.out.println();
		
		System.out.println("Reservations: ");
		flight.reserveSeat("Alex", SeatClass.FIRST_CLASS);
		flight.reserveSeat("Clive", SeatClass.BUSINESS_CLASS);
		flight.reserveSeat("James", SeatClass.FIRST_CLASS);
		flight.reserveSeat("Mary", SeatClass.ECONOMY_CLASS);
		flight.reserveSeat("Dirk", SeatClass.ECONOMY_CLASS);
		flight.reserveSeat("Silke", SeatClass.ECONOMY_CLASS);
		flight.reserveSeat("Amy", SeatClass.BUSINESS_CLASS);
		flight.reserveSeat("Peter", SeatClass.ECONOMY_CLASS);
		flight.reserveSeat("Betty", SeatClass.ECONOMY_CLASS);
		System.out.println();
		flight.displayPassengerList();
		
		System.out.println("\n");
		
		System.out.println("Last minute cancelations: ");
		flight.cancelReservation("Silke");
		flight.cancelReservation("Alex");
		flight.cancelReservation("Amy");
		System.out.println();
		flight.displayPassengerList();
		
		System.out.println();
		
		double totalRevenue = flight.calculateTotalRevenue();
		System.out.println("Total Revenue generated by the flight: €" + totalRevenue);
	}

}
